name: Build

on:
  workflow_call: {}

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Lambda
        run: pnpm run build

      - name: Prune dev dependencies
        run: pnpm prune --prod

      - name: Package
        run: zip -r dist/function.zip dist node_modules package.json

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: dist/function.zip
