name: Notifications Lambda Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  git:
    if: github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)
    uses: ./.github/workflows/git.yml

  build:
    needs: [git]
    uses: ./.github/workflows/build.yml

  terraform:
    needs: [build]
    name: Terraform
    strategy:
      matrix:
        environment: [stg, prd]
      fail-fast: false
    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ matrix.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  release:
    needs: [git]
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/release.yml
